const BACKTEST = {
  INITIATED: "EVENT/BACKTEST/INITIATED",
  UPDATE: "EVENT/BACKTEST/UPDATE",
  COMPLETED: "EVENT/BACKTEST/COMPLETED",
};

module.exports = {
  EVENT: {
    BACKTEST,
    STORE_MARKET_FEED: (SCRIP) => `EVENT/STORE_MARKET_FEED/${SCRIP}`,
  },
};
